services:
  - type: web
    name: eshipz-mcp
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py --sse
    envVars:
      - key: API_BASE_URL
        value: https://app.eshipz.com
      - key: USE_SSE
        value: true
      - key: ESHIPZ_TOKEN
        sync: false
      - key: PORT
        value: 10000
